### ISSUE TITLE
the image can not become bigger when it's in <Modal/>

### ISSUE THREAD

**Issue by timzaak** [ldn0x7dc/react-native-transformable-image#5] opened 2016-07-15 10:52 UTC
```
import React from 'react';
import Image from 'react-native-transformable-image';
import { Modal, Dimensions, View } from 'react-native'
const { width, height } = Dimensions.get('window');
export default class TestImageView extends React.Component {
  render() {
    return (
      <Modal
        animationType={"none"}
        transparent={false}
        visible={true}
      >
        <View style={{flex: 1, alignItems: 'center'}}>
          <Image
            style={{width: width, height: height}}
            source={{ uri:'http://g.hiphotos.baidu.com/baike/pic/item/a8014c086e061d956cfdba6979f40ad162d9ca2c.jpg' }}
            pixels={{width:450,height:313}}

          />
        </View>
      </Modal>);
  }
}

```

it can not become bigger with 2 fingers, both in android and ios

**Comment by doochik** [comment] 2016-07-15 11:30
I have the same problem with react-native-gallery which used this module
https://github.com/ldn0x7dc/react-native-gallery/issues/6

**Comment by vaibhawc** [comment] 2016-07-18 08:31
I am facing it too. Also double tap doesn't work. Must it be handled separately?

**Comment by ldn0x7dc** [comment] 2016-07-21 10:43
@timzaak @doochik The pinch gesture issue inside a modal should be fixed with latest release(0.0.18). A modal will swallow the gesture if fingers >= 2. It's weird.
@vaibhawc I can't reproduce the double tap issue. Are you using an Android device?

**Comment by doochik** [comment] 2016-07-21 17:56
@ldn0x7dc thanks!

**Closed as completed** 2016-07-22 02:34 UTC

**Comment by vaibhawc** [comment] 2016-08-26 16:02
@Idn0x7dc, I apologize for being very late. I had to postpone working on this thing. 
I am using it on ios and I went through the code, I can't figure out why double tap must not work.
